# FIX: wait for mysql to start
version: '3'
services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: api-server
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
